# Generated by Django 5.2.3 on 2025-07-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subject',
        ),
    ]
