# Generated by Django 5.2.3 on 2025-07-30 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='users.teacherprofile'),
        ),
    ]
