#api for creating custom user
###

POST http://127.0.0.1:8000/api/users/register/
Authorization: Basic admin:admin
Content-Type: application/json

{
  "username": "subin",
  "password": "password@123",
  "user_type": "teacher",
  "department_name": "CSE"
  
}

#api call for login user
###

POST http://127.0.0.1:8000/api/users/login/
Content-Type: application/json

{
  "username":"subin",
  "password":"password@123"
}

#api call for student detail
###

GET http://127.0.0.1:8000/api/users/student/44/
Authorization: Basic subin:password@123



#api call for updating a student
###

PUT http://127.0.0.1:8000/api/users/student/44/
Content-Type: application/json
Authorization: Basic admin:admin

{
  "department_name":"Mech"

}

#api call for deleting a student
###

DELETE http://127.0.0.1:8000/api/users/student/49/
Authorization: Basic admin:admin

#api call for listing students
###

GET http://127.0.0.1:8000/api/users/student/
Authorization: Basic subin:password@123

#api call for listing teachers
###

GET http://127.0.0.1:8000/api/users/teacher/
Authorization: Basic admin:admin

#api call for deleting a teacher
###
DELETE http://127.0.0.1:8000/api/users/teacher/4/

#api cal for updating a teacher
###

PUT http://127.0.0.1:8000/api/users/teacher/2/
Content-Type: application/json

{

    "username": "john",
    "email": "john@gmail.com",
    "user_type": "teacher",
    "subject": "Science"
}

#api cal for retrieving a teacher
###

GET http://127.0.0.1:8000/api/users/teacher/1/