#api for creating custom user
###

POST http://127.0.0.1:8000/api/users/register/
Authorization: Basic admin:admin
Content-Type: application/json

{
  "username": "teacher_mech3",
  "password": "password@123",
  "user_type": "teacher",
  "department_name": "MECH",
  "is_hod": false
}

#api call for login user
###

POST http://127.0.0.1:8000/api/users/login/
Content-Type: application/json

{
  "username":"teacher_cse2",
  "password":"password@123"
}

#api call for listing teachers
###

GET http://127.0.0.1:8000/api/users/teachers/
Authorization: Basic admin:admin

#api call for listing students
###

GET http://127.0.0.1:8000/api/users/students/
Authorization: Basic teacher_cse1:password@123

#api call for creating subjects
###
POST http://127.0.0.1:8000/api/users/subjects/create/
Authorization: Basic admin:admin
Content-Type: application/json

{
  "name": "Electrical engineering",
  "department_name": "ECE"
}

###
#api call for listing subjects in a department

GET http://127.0.0.1:8000/api/users/subjects/department/3/

###
#api call for updating and deleting a subject

PUT http://127.0.0.1:8000/api/users/subjects/1/
Authorization: Basic admin:admin
Content-Type: application/json

{
  "name": "Advanced Python"
}

###
#api call for deleting a subject

DEL http://127.0.0.1:8000/api/users/subjects/3/
Authorization: Basic admin:admin

#api call for student detail
###

GET http://127.0.0.1:8000/api/users/student/11/
Authorization: Basic teacher_cse2:password@123



#api call for updating a student
###

PUT http://127.0.0.1:8000/api/users/student/60/
Content-Type: application/json
Authorization: Basic admin:admin

{
  "department":{ 
    "id":1,
    "name":"ECE"   
  
}
}
#api call for deleting a student
###

DELETE http://127.0.0.1:8000/api/users/student/61/
Authorization: Basic admin:admin

#api call for listing students
###

GET http://127.0.0.1:8000/api/users/student/
Authorization: Basic subin:password@123

#api call for listing teachers
###

GET http://127.0.0.1:8000/api/users/teacher/
Authorization: Basic admin:admin

#api call for deleting a teacher
###
DELETE http://127.0.0.1:8000/api/users/teacher/4/

#api cal for updating a teacher
###

PUT http://127.0.0.1:8000/api/users/teacher/2/
Content-Type: application/json

{


}

#api cal for retrieving a teacher
###

GET http://127.0.0.1:8000/api/users/teacher/1/